# Generated by Django 6.0.7 on 2026-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='image ou vidéo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.CharField(blank=True, max_length=1000, verbose_name='message'),
        ),
    ]
