# Generated by Django 6.0.7 on 2026-07-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'échange',
                'verbose_name_plural': 'échanges',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PossessionCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'carte possédée',
                'verbose_name_plural': 'cartes possédées',
                'ordering': ['-date_obtention'],
            },
        ),
    ]
