# Generated by Django 6.0.7 on 2026-07-12 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='echange',
            name='proposant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges_proposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='echange',
            name='receveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possessioncarte',
            name='collectionneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_possedees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possessioncarte',
            name='pokemone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='comptes.pokemone'),
        ),
        migrations.AddField(
            model_name='echange',
            name='carte_demandee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collection.possessioncarte'),
        ),
        migrations.AddField(
            model_name='echange',
            name='carte_proposee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collection.possessioncarte'),
        ),
        migrations.AlterUniqueTogether(
            name='possessioncarte',
            unique_together={('collectionneur', 'pokemone')},
        ),
    ]
