# Generated by Django 6.0.7 on 2026-07-12 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('dresseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adhésion',
                'verbose_name_plural': 'adhésions',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, verbose_name='nom')),
                ('type', models.CharField(choices=[('feu', 'Feu'), ('eau', 'Eau'), ('plante', 'Plante'), ('electrik', 'Électrik'), ('psy', 'Psy'), ('tenebres', 'Ténèbres'), ('dragon', 'Dragon'), ('normal', 'Normal')], max_length=20, verbose_name='type associé')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='description')),
                ('prive', models.BooleanField(default=False, verbose_name='groupe privé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membres', models.ManyToManyField(related_name='groupes', through='groupes.Adhesion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'groupe',
                'verbose_name_plural': 'groupes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='adhesion',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupes.groupe'),
        ),
        migrations.AlterUniqueTogether(
            name='adhesion',
            unique_together={('dresseur', 'groupe')},
        ),
    ]
