# Generated by Django 6.0.7 on 2026-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemone',
            name='modele_3d',
            field=models.CharField(blank=True, choices=[('raccoony', 'Raccoony'), ('rouage', 'Rouage'), ('planetin', 'Planétin'), ('astrelin', 'Astrelin'), ('ailune', 'Ailune')], max_length=20, verbose_name='modèle 3D'),
        ),
    ]
