# Generated by Django 6.0.7 on 2026-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_pokemone_modele_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemone',
            name='affection',
            field=models.PositiveIntegerField(default=0, verbose_name='affection'),
        ),
    ]
