# Generated by Django 6.0.7 on 2026-07-12 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=1000, verbose_name='contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='image')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('aimes_par', models.ManyToManyField(blank=True, related_name='posts_aimes', to=settings.AUTH_USER_MODEL)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=300, verbose_name='contenu')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='social.post')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('suiveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'permissions': [('moderer_abonnement', 'Peut modérer (forcer la suppression) un abonnement')],
                'unique_together': {('suiveur', 'suivi')},
            },
        ),
    ]
