# Generated by Django 6.0.7 on 2026-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_commentaire_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/', verbose_name='photo ou vidéo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=models.TextField(blank=True, max_length=1000, verbose_name='contenu'),
        ),
    ]
